kind: pipeline
type: docker
name: batman-pipeline-with-notif

steps:
- name: test-gadget
  image: python:3.9-slim
  commands:
  - python gadget_test.py

- name: notify-batman
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    port: 587
    from: batcave-ci@gmail.com
    recipients: [ your-email@example.com ]
  when:
    status: [ success, failure ] # TASK 11.2: Send mail on any status
