kind: pipeline
type: docker
name: batman-gadget-test

steps:
- name: task-4-checkout-proof
  image: alpine
  commands:
  - ls -la  # Shows gadget_test.py in the workspace (Task 4 Proof)

- name: task-3-and-5-run-test
  image: python:3.9-slim
  commands:
  - python gadget_test.py  # Runs your code (Task 3 & 5 Proof)

trigger:
  event:
  - push  # Triggers automatically on GitHub commit (Task 5)
