kind: pipeline
type: docker
name: task-3-workspace-commands

steps:
- name: create-and-list
  image: alpine
  commands:
  - pwd  # TASK 3.1: Navigate/Show current workspace path
  - echo "Assignment Task 3: File successfully created by Vasanth" > build_report.txt # TASK 3.2: Create a text file
  - ls -l # Proof of file creation in workspace

- name: display-content
  image: alpine
  commands:
  - cat build_report.txt # TASK 3.3: Display file contents in console
