kind: pipeline
type: docker
name: task-5-automatic-trigger

steps:
- name: check-code-change
  image: alpine
  commands:
  - echo "Task 5: Webhook detected a code change in IamBatman repo!"
  - date  # Shows exactly when the build was triggered

trigger:
  event:
  - push  # This is the modern equivalent of "Polling"
