kind: pipeline
type: docker
name: batman-pipeline

steps:
- name: task-12-git-check
  image: alpine
  commands:
  - git remote -v
  - echo "Remote Repo Verified"

- name: task-3-gadget-test
  image: python:3.9-slim
  commands:
  - python gadget_test.py

trigger:
  event:
    - push
