kind: pipeline
type: docker  # This tells the Master to find a 'Docker Runner' (Slave)
name: task-9-node-management

platform:
  os: linux
  arch: amd64

steps:
- name: check-node-info
  image: alpine
  commands:
  - uname -a  # This command displays the details of the 'Slave' node
  - echo "Task 9: Master-Slave communication verified on IamBatman repo"
