kind: pipeline
type: docker
name: batman-pipeline

steps:
- name: task-4-checkout
  image: alpine
  commands:
  - ls -la  # Proves code is in workspace

- name: task-3-and-5-run
  image: python:3.9-slim
  commands:
  - python gadget_test.py  # Runs your gadget

- name: task-6-parameter
  image: alpine
  environment:
    GADGET_NAME: Batarang
  commands:
  - echo "Testing gadget variable $${GADGET_NAME}"

trigger:
  event:
    - push
    - cron
