kind: pipeline
type: docker
name: Project-A-Build  # This is the "Upstream" job

steps:
- name: compile-gadget
  image: alpine
  commands:
  - echo "Project A: Compiling Batman's gadget..."
  - sleep 5

---
kind: pipeline
type: docker
name: Project-B-Test   # This is the "Downstream" job

steps:
- name: test-gadget
  image: python:3.9-slim
  commands:
  - echo "Project B: Triggered because Project A was successful!"
  - python gadget_test.py

depends_on:
- Project-A-Build  # This creates the link between Project A and B
