kind: pipeline
type: docker
name: batman-pipeline

steps:
- name: task-12-remote-verification
  image: alpine
  commands:
  - git remote -v
  - echo "Task 12: Remote Repository Pulled Successfully"

- name: task-3-gadget-execution
  image: python:3.9-slim
  commands:
  - python gadget_test.py

trigger:
  event:
    - push
    - cron
