kind: pipeline
type: docker
name: batman-assignment-pipeline

steps:
- name: task-3-workspace
  image: alpine
  commands:
  - pwd
  - echo "Batman Workspace Verified" > report.txt

- name: task-4-and-5-run
  image: python:3.9-slim
  commands:
  - ls -la
  - python gadget_test.py

- name: task-6-parameters
  image: alpine
  environment:
    GADGET_NAME: Batarang
  commands:
  - echo "Testing gadget variable $${GADGET_NAME}"

trigger:
  event:
    - push
    - cron
