kind: pipeline
type: docker
name: batman-assignment

steps:
- name: task-12-remote-repo
  image: alpine
  commands:
  - git remote -v
  - echo "Task 12: Remote Repository Verification Successful"

- name: task-3-gadget-run
  image: python:3.9-slim
  commands:
  - python gadget_test.py

trigger:
  event:
    - push
    - cron
