kind: pipeline
type: docker
name: batman-full-pipeline

steps:
- name: stage-1-build
  image: alpine
  commands:
  - echo "Building Batman Gadgets..."
  - ls -la # Task 4: Git check

- name: stage-2-test
  image: python:3.9-slim
  commands:
  - python gadget_test.py # Task 3: Command execution

- name: stage-3-deploy
  image: alpine
  commands:
  - echo "Deploying to Bat-Cave server..."
  - echo "Task 10 Pipeline Complete!"

trigger:
  event:
    - push
    - cron
