kind: pipeline
type: docker
name: default

steps:
- name: task-12-remote
  image: alpine
  commands:
  - git remote -v
  - echo "Task 12 Verified"

- name: task-3-test
  image: python:3.9-slim
  commands:
  - python gadget_test.py
