kind: pipeline
type: docker
name: batman-pipeline

steps:
- name: task-3-and-4
  image: python:3.9-slim
  commands:
  - ls -la
  - python gadget_test.py

- name: task-6-parameters
  image: alpine
  environment:
    GADGET_NAME: Batarang
  commands:
  - echo "Testing gadget: $${GADGET_NAME}"

trigger:
  event:
  - push
  - cron
