kind: pipeline
type: docker
name: task-3-workspace

steps:
- name: create-step
  image: alpine
  commands:
  - pwd  # This shows the workspace path (Task 3.1)
  - echo "Batman's Secret Report" > report.txt # (Task 3.2)

- name: display-step
  image: alpine
  commands:
  - cat report.txt # (Task 3.3)
