kind: pipeline
type: docker
name: task-6-parameters

steps:
- name: run-parameterized-test
  image: python:3.9-slim
  environment:
    GADGET_NAME: "Batarang"  # This is your parameter
  commands:
  - echo "Current Gadget being tested is $${GADGET_NAME}"
  - python gadget_test.py
