kind: pipeline
type: docker
name: batman-pipeline

steps:
- name: task-4-git-verify
  image: alpine
  commands:
  - ls -la

- name: task-3-and-5-run
  image: python:3.9-slim
  commands:
  - python gadget_test.py

- name: task-6-parameter
  image: alpine
  environment:
    GADGET_NAME: Batarang
  commands:
  - echo "Testing gadget variable $${GADGET_NAME}"

trigger:
  event:
    - push
    - cron
