kind: pipeline
type: docker
name: task-12-remote-repo

steps:
- name: verify-remote-source
  image: alpine
  commands:
  - echo "Task 12: Verifying Remote Connection"
  - git remote -v  # This command shows the GitHub URL (Proof for 12.1)
  - git log -1     # This shows the latest commit pulled from the remote (Proof for 12.2)

trigger:
  event:
    - push
