kind: pipeline
type: docker
name: batman-pipeline

steps:
- name: task-12-remote-pull
  image: alpine
  commands:
  - git remote -v
  - echo "Task 12: Successfully pulled from Remote GitHub Repo"

- name: task-3-and-5-run
  image: python:3.9-slim
  commands:
  - python gadget_test.py

- name: task-11-notif
  image: alpine
  commands:
  - echo "Notification: Build complete for IamBatman"
  when:
    status:
    - success
    - failure

trigger:
  event:
    - push
    - cron
