kind: pipeline
type: docker
name: batman-pipeline

steps:
- name: task-10-build-stage
  image: alpine
  commands:
  - echo "Building Gadgets..."
  - ls -la

- name: task-3-and-5-test-stage
  image: python:3.9-slim
  commands:
  - python gadget_test.py

- name: task-11-notification-logic
  image: alpine
  commands:
  - echo "Build Status is COMPLETE. Sending notification to Bat-Cave..."
  when:
    status:
    - success
    - failure

trigger:
  event:
    - push
    - cron
